### ISSUE TITLE
"husarion_whoami" package not found (Demo README guide)

### ISSUE THREAD

**Issue by pijaro** [RobotecAI/rai#153]
**Describe the bug**

When following the Demo README, running `ros2 run rai_whoami rai_whoami_node --ros-args -p robot_description_package:="husarion_whoami"` returns an error with missing `husarion_whoami` package.

```bash
ament_index_python.packages.PackageNotFoundError: "package 'husarion_whoami' not found, searching: [...]
```

**To Reproduce**

1. Follow rai [Quick start](https://github.com/RobotecAI/rai?tab=readme-ov-file#quick-start)
2. Follow the first point in Demo README: [Running rai](https://github.com/RobotecAI/rai/blob/development/docs/demos.md#running-rai)

**Expected behavior**
The node starts correctly.

**Platform**

- OS: Ubuntu 24.04
- ROS 2 Jazzy

**Version**
ddb5c6eae3cb821fae2f708abd7c45427b24b034

**Additional context**
The first problem is the package name, the [Demo README](https://github.com/RobotecAI/rai/blob/development/docs/demos.md#running-rai) should mention the new name: `rosbot_xl_whoami`.

The second problem is that the package is not built and the `ros2 run` can't find it.

The fix is to rebuild this package only and re-source the workspace.

```bash
colcon build --symlink-install --packages-select rosbot_xl_whoami
. ./install/setup.bash
```

**Comment by maciejmajek** [comment]
Thank you for PR. Merged!
