### ISSUE TITLE
Rosbot xl generic node demo: "tf_transformations" module missing in a workspace

### ISSUE THREAD

**Issue by pijaro** [RobotecAI/rai#154]
**Describe the bug**
Running "python examples/rosbot-xl-generic-node-demo.py" returns with an error:

```bash
ModuleNotFoundError: No module named 'tf_transformations'
```

**To Reproduce**

1. Follow the [Demo readme: running rai](https://github.com/RobotecAI/rai/blob/development/docs/demos.md#running-rai)
2. Run `python examples/rosbot-xl-generic-node-demo.py`

**Expected behavior**
The node runs correctly.

**Platform**

- OS: Ubuntu 24.04
- ROS 2 Jazzy

**Version**
ddb5c6eae3cb821fae2f708abd7c45427b24b034

**Additional context**
Installing `sudo apt-get install ros-jazzy-tf-transformations` solves the problem.

**Comment by maciejmajek** [comment]
Fixed in [e0cff74](https://github.com/RobotecAI/rai/blob/e0cff74cf4a0275a3301a3061442d60797297b57/src/rai/package.xml#L18)
