### ISSUE TITLE
Chat interface has no access to some tools when running HMI without the "whoami" parameter.

### ISSUE THREAD

**Issue by pijaro** [RobotecAI/rai#156]
**Describe the bug**
Running the HMI without robot description parameter:

```
streamlit run src/rai_hmi/rai_hmi/streamlit_hmi_node.py
```

has some limitations, ie. it can't fetch the camera output.

When specifying the robot description, for example

```
ros2 run rai_whoami rai_whoami_node --ros-args -p robot_description_package:="rosbot_xl_whoami"
streamlit run src/rai_hmi/rai_hmi/streamlit_hmi_node.py rosbot_xl_whoami
```

then everything is fine.

Is it expected behavior? If so, maybe some user feedback could be helpful. Also README should mention any limitations.

**To Reproduce**

1. Run demo simulation
2. Run `streamlit run src/rai_hmi/rai_hmi/streamlit_hmi_node.py`
3. Ask for camera output.
4. Camera output is not displayed, the error mentions that the `rclpy.Node object has no attribute 'get_raw_message_from_topic'`

**Expected behavior**
An image from the camera.

**Platform**

- OS:Ubuntu 22.04
- ROS 2 Humble

**Version**
e0cff74cf4a0275a3301a3061442d60797297b57

**Comment by maciejmajek** [comment]
> Is it expected behavior? If so, maybe some user feedback could be helpful. Also README should mention any limitations.

It is for now. We are currently working on [HMI refactor](https://github.com/RobotecAI/rai/pull/143). README will also be updated. Thank you!
