### ISSUE TITLE
Switch to logs from filter node

### ISSUE THREAD

**Issue by adamdbrw** [RobotecAI/rai#170]
**Is your feature request related to a problem? Please describe.**
There is a dedicated ROS 2 log filter and aggregation node, which has more features & parameters and is likely / potentially more performant than current python code. It is best to switch state update node to use it. 

**Describe the solution you'd like**
State node calls service to get logs from the node.

**Describe alternatives you've considered**
Feeding all the logs to a cheaper AI model for filtering and summarizing. This could be resource intensive for some systems though and most of the useful filtering can be done well without any AI.

**Additional context**
Logs are important for the robot to understand its own state and to help users debug it.

**Comment by maciejmajek** [comment]
Done under #314 and #322
