### ISSUE TITLE
Create ros2 launch file to run rosbot XL demo

### ISSUE THREAD

**Issue by boczekbartek** [RobotecAI/rai#172]
**Is your feature request related to a problem? Please describe.**
Currently, rosbot-XL demo requires running the simulation binary, navigation stack, and RAI nodes manually.

**Describe the solution you'd like**
It would be convenient to run this demo using the `ros2 launch` command.

**Additional context**
Current workflow is described in: https://github.com/RobotecAI/rai/blob/development/docs/demos.md

**Comment by iampaulidrobo** [comment]
Hello,
Can I work on this?

**Comment by maciejmajek** [comment]
Hi @iampaulidrobo. Thank you for taking interest in RAI. This launch file is crucial for our ROSCon2024 demos and therefore will be assigned to @boczekbartek as he is the main developer of the demo. Is there anything else you would like to tackle?

**Comment by boczekbartek** [comment]
This issue has been resolved by: https://github.com/RobotecAI/rai/pull/291
